# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/camera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/oneplus/camera


PRODUCT_PACKAGES += \
    OplusAppPlatform \
    OplusCamera
